name: osip_app
description: Osip schedule application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  equatable: ^2.0.5
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.2
  sqflite: ^2.2.6
  floor: ^1.4.1
  csv: ^5.0.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  floor_generator: ^1.4.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/gtfs/